### ISSUE TITLE
canteen drink has issue from 100->75

### ISSUE THREAD

**Issue by omid429** [JusCampin/oss_water#1]
The canteen is a nice little touch. I really like how you managed to create it without having to maintain a table to keep track of the progress. Nicely done. I added it to my server and bought a full canteen and it kept disappearing after the first drink (100 --> 75). I gave myself a 75% canteen and went through the rest of the motions with no issue. Drank it all then filled it up and it worked perfectly. Then again, after taking the first drink from a full canteen, disappeared from inventory again. Been staring at it and for the life of me can not figure it out. Also, the animation is different between that drink and the rest.

You think this could help you server side?

local canteenInv = "canteen100"
local canteenNewID = "canteen"....tostring(string.sub(v,5) - 25)

replace canteen100 with source and then add an 'if' to check for canteen0.

**Comment by JusCampin** [comment]
Thank you for the feedback. It was using the old vorp api. I did a quick update and in my testing all is working now.  
I've changed the name to fall in line with my other scripts. More updates and some new stuff will be coming soon.

**Comment by zurv4n** [comment]
still having the same issue. works on all levels, but not full

**Comment by JusCampin** [comment]
I just tested again and it's working perfectly from full to empty. My test server is running fully updated vorp scripts. Are your core and inventory scripts up to date? If so, maybe another script is interfering.

**Comment by zurv4n** [comment]
It is having a conflict with vorp metabolism. disabled that and everything worked perfect.

**Comment by JusCampin** [comment]
It's working fine with vorp_metabolism in default state. Is it up to date? Is it a config issue with something you added?

**Comment by zurv4n** [comment]
I had a different version of the script b/c I wanted a different hud. Your script works perfect now. I had to edit metabolism to give me the hud I wanted.

Thank you again and I look forward to what you have coming out next.
